import React from 'react';
import Providers from './Providers';
import Header from './components/Header';
import Footer from './components/Footer';
import './styles/reset.css';
import './styles/global.css';

export const metadata = {
	title: 'Mario\'s Tattoos',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {

	return (
		<html lang='en'>
			<Providers>
				<body className='flex flex-col gap-4 px-6 py-6 transition-colors duration-1000 lg:px-60'>
					<Header />
					{children}
					<Footer />
				</body>
			</Providers>
		</html>
	);
}
