import React from 'react';
import Providers from './Providers';
import Header from './components/Header';
import Footer from './components/Footer';
import './styles/reset.css';
import './styles/global.css';

export const metadata = {
	title: 'Mario\'s Portfolio',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="en">
			<Providers>
				<body>
					<Header />
					{children}
					<Footer />
				</body>
			</Providers>
		</html>
	);
}
